In [1]:
import numpy as np

In [3]:
#print 1-D array
array_1d=np.array([1,2,3,4])
print(array_1d)

[1 2 3 4]


In [8]:
#find type of Array
type(array_1d)

numpy.ndarray

In [9]:
# Dimension of Array
array_1d.ndim


1

In [7]:
#print 2-D array
array_2d=np.array([[1,2,3],[3,5,6],[8,6,5]])
print(array_2d)

[[1 2 3]
 [3 5 6]
 [8 6 5]]


In [13]:
type(array_2d)


numpy.ndarray

In [15]:
array_2d.ndim

2

In [29]:
#(row, colummn)
array_2d.shape

(3, 3)

In [24]:
#print 3-D Array
array_3d=np.array([[[1,3,4],[2,4,6],[9,6,8]] ,[[1,5,6],[2,6,8],[3,6,9]],[[1,4,6],[2,4,6],[2,6,9]]])
print(array_3d)

[[[1 3 4]
  [2 4 6]
  [9 6 8]]

 [[1 5 6]
  [2 6 8]
  [3 6 9]]

 [[1 4 6]
  [2 4 6]
  [2 6 9]]]


In [25]:
type(array_3d)

numpy.ndarray

In [26]:
array_3d.ndim

3

In [27]:
#Find array size
array_3d.size

27

In [28]:
#Find array shape
array_3d.shape

(3, 3, 3)